-- Institution backfill, NORMALIZED (supersedes section 4 of 20260807150000 — run THIS instead).
--
-- Values come from a CURATED domain->institution map (hand-verified proper names), NOT from the
-- institution strings already in the KG. Those are NIH-RePORTER derived and dirty: they contain
-- multi-organization values ('NEW YORK UNIVERSITY, UNIVERSITY OF ALABAMA AT BIRMINGHAM'),
-- truncations ('DUKE'), and at least one wrong row (an ee.columbia.edu address mapped to
-- 'NEW YORK UNIVERSITY SCHOOL OF MEDICINE'). Fuzzy-matching against them also produced a real
-- error: 'University of Pennsylvania' -> 'PENNSYLVANIA STATE UNIVERSITY'. So we normalize to
-- clean canonical names instead of propagating that mess.
--
-- 112 of 119 resolved from the curated map; 7 kept exactly as the member typed them (personal
-- domains like gmail.com, where the domain carries no institutional signal).
-- FILL-ONLY-EMPTY and idempotent: only writes where institution is currently NULL/empty.

UPDATE public.investigators i SET institution = v.inst
FROM (VALUES
  ('aw4614@nyu.edu', 'New York University'),
  ('tianqing.li@duke.edu', 'Duke University'),
  ('stephen.heisig@mssm.edu', 'Icahn School of Medicine at Mount Sinai'),
  ('oruebel@lbl.gov', 'Lawrence Berkeley National Laboratory'),
  ('jkw131@psu.edu', 'Pennsylvania State University'),
  ('han.yi@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('kebouchard@berkeley.edu', 'University of California, Berkeley'),
  ('erik.c.johnson@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('yvonne.bennett@nih.gov', 'National Institutes of Health'),
  ('simmonsj@mail.nih.gov', 'National Institutes of Health'),
  ('mattson.ogg@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('neha.thomas@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('nicole.guittari@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('mvallejomartelo@mednet.ucla.edu', 'University of California, Los Angeles'),
  ('alireza.kazemi@utah.edu', 'University of Utah'),
  ('y.li7@columbia.edu', 'Columbia University'),
  ('ghp2114@cumc.columbia.edu', 'Columbia University Irving Medical Center'),
  ('mekline@mit.edu', 'Massachusetts Institute of Technology'),
  ('hz2555@columbia.edu', 'Columbia University'),
  ('kgothard@arizona.edu', 'University of Arizona'),
  ('kailin.zhuang@berkeley.edu', 'University of California, Berkeley'),
  ('rahul.hingorani@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('jylboline@informedminds.info', 'Informed Minds Inc.'),
  ('ckendell@seas.upenn.edu', 'University of Pennsylvania'),
  ('vprakash@miami.edu', 'University of Miami'),
  ('lauren.diaz@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('yoh@dartmouth.edu', 'Dartmouth College'),
  ('nicole.stock@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('jeffmun@uw.edu', 'University of Washington'),
  ('estesa@uw.edu', 'University of Washington'),
  ('kate.macduffie@seattlechildrens.org', 'Seattle Children''s Research Institute'),
  ('robertstim@chop.edu', 'Children''s Hospital of Philadelphia'),
  ('tstjohn@uw.edu', 'University of Washington'),
  ('tlancaster6@gatech.edu', 'Georgia Institute of Technology'),
  ('te137@echo.rutgers.edu', 'Rutgers University'),
  ('sx67@scarletmail.rutgers.edu', 'Rutgers University'),
  ('kimm8@chop.edu', 'Children''s Hospital of Philadelphia'),
  ('blaskey@chop.edu', 'Children''s Hospital of Philadelphia'),
  ('sandy.hider@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('dana.schloesser@nih.gov', 'National Institutes of Health'),
  ('awu36@gatech.edu', 'Georgia Institute of Technology'),
  ('pesaran@upenn.edu', 'University of Pennsylvania'),
  ('jarl.haggerty@pennmedicine.upenn.edu', 'University of Pennsylvania'),
  ('sequioasmith@ufl.edu', 'University of Florida'),
  ('afeinsinger@mednet.ucla.edu', 'University of California, Los Angeles'),
  ('sgoering@uw.edu', 'University of Washington'),
  ('kleineuw@uw.edu', 'University of Washington'),
  ('kuschnere@chop.edu', 'Children''s Hospital of Philadelphia'),
  ('samaras@cs.stonybrook.edu', 'Stony Brook University'),
  ('brent.kious@hsc.utah.edu', 'University of Utah'),
  ('rly@lbl.gov', 'Lawrence Berkeley National Laboratory'),
  ('smprince@lbl.gov', 'Lawrence Berkeley National Laboratory'),
  ('talbarran3@gatech.edu', 'Georgia Institute of Technology'),
  ('cody.c.baker.phd@gmail.com', 'Dartmouth College'),
  ('yibei@mit.edu', 'Massachusetts Institute of Technology'),
  ('wn15@rice.edu', 'Rice University'),
  ('brian.gitahi@yale.edu', 'Yale University'),
  ('karen.david@nih.gov', 'National Institutes of Health'),
  ('abigayle.fogarty@mssm.edu', 'Icahn School of Medicine at Mount Sinai'),
  ('katherine.dokholyan@mssm.edu', 'Icahn School of Medicine at Mount Sinai'),
  ('grace.hwang@nih.gov', 'National Institutes of Health'),
  ('acabral30@gatech.edu', 'Georgia Institute of Technology'),
  ('uros.topalovic@duke.edu', 'Duke University'),
  ('mauricio.rangel-gomez@nih.gov', 'National Institutes of Health'),
  ('la.garcia@utah.edu', 'University of Utah'),
  ('sugavanam.3@osu.edu', 'The Ohio State University'),
  ('chang.1560@osu.edu', 'The Ohio State University'),
  ('stellachang1114@g.ucla.edu', 'University of California, Los Angeles'),
  ('thore@umich.edu', 'University of Michigan'),
  ('alvarovh@umich.edu', 'University of Michigan'),
  ('teneille.brown@law.utah.edu', 'University of Utah'),
  ('marcia.patchan@jhuapl.edu', 'Johns Hopkins University Applied Physics Laboratory'),
  ('weikang.shi@yale.edu', 'Yale University'),
  ('meghan.cum@yale.edu', 'Yale University'),
  ('david.ostry@yale.edu', 'Yale University'),
  ('taylor.wise@yale.edu', 'Yale University'),
  ('amelia.johnson.aj764@yale.edu', 'Yale University'),
  ('gao0624@gmail.com', 'Northwestern University'),
  ('vincent.gracco@yale.edu', 'Yale University'),
  ('mvperdue16@gmail.com', 'UMass Chan Medical School'),
  ('sulstice@mit.edu', 'Massachusetts Institute of Technology'),
  ('adam@adamnoah.com', 'Yale University'),
  ('amrita.nair@yale.edu', 'Yale University'),
  ('yizuo@ucsc.edu', 'University of California, Santa Cruz'),
  ('a.macaskill@ucl.ac.uk', 'University College London'),
  ('wanchenlin@berkeley.edu', 'University of California, Berkeley'),
  ('shannon.gourley@emory.edu', 'Emory University'),
  ('joseph.monaco@nih.gov', 'National Institutes of Health'),
  ('holly.moore@nih.gov', 'National Institutes of Health'),
  ('mark.tiede@yale.edu', 'Yale University'),
  ('kari.johnson@nih.gov', 'National Institutes of Health'),
  ('eunyoung.kim@nih.gov', 'National Institutes of Health'),
  ('adallave@ucla.edu', 'University of California, Los Angeles'),
  ('joostw@seas.upenn.edu', 'University of Pennsylvania'),
  ('cz2715@columbia.edu', 'Columbia University'),
  ('mpg8611@nyu.edu', 'New York University'),
  ('karmiella.ferster@mssm.edu', 'Icahn School of Medicine at Mount Sinai'),
  ('mbaylis@berkeley.edu', 'University of California, Berkeley'),
  ('sara.sanchez.alonso@yale.edu', 'Yale University'),
  ('aydintasevac@gmail.com', 'University of Utah'),
  ('kaysuninf@gmail.com', 'Columbia Univerisity / Mount Sanai volunteer'),
  ('joseph.colonel@mssm.edu', 'Icahn School of Medicine at Mount Sinai'),
  ('nm4075@nyu.edu', 'New York University'),
  ('lensky.augustin@psych.utah.edu', 'University of Utah'),
  ('adam.friedman2@mssm.edu', 'Icahn School of Medicine at Mount Sinai'),
  ('calebsj@sas.upenn.edu', 'University of Pennsylvania'),
  ('nishant.rao@yale.edu', 'Yale University'),
  ('emily@basis.ai', 'Basis Research Institute'),
  ('ralph@basis.ai', 'Basis Research Institute'),
  ('bmimica@princeton.edu', 'Princeton University'),
  ('dima@basis.ai', 'Basis Research Institute'),
  ('jongwoon.kim@nyulangone.org', 'NYU Langone Health'),
  ('brendan.ito@nyulangone.org', 'NYU Langone Health'),
  ('hongli.wang@berkeley.edu', 'University of California, Berkeley'),
  ('tdaniel60@gatech.edu', 'Georgia Institute of Technology'),
  ('timbr@uw.edu', 'University of Washington'),
  ('bbqs.test.user.tier1@gmail.com', 'MIT'),
  ('ndrnkbkht@gmail.com', 'MIT'),
  ('sjuliani@andrew.cmu.edu', 'Carnegie Mellon University')
) AS v(email, inst)
WHERE lower(i.email) = v.email
  AND coalesce(nullif(trim(i.institution), ''), '') = '';