// This file is automatically generated but has been intentionally modified:
// storage uses a shared domain cookie so agent.brain-bbqs.org inherits the session.
// All connection values are env-driven so the same codebase can target prod or sandbox.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { cookieStorage } from './cookie-storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vpexxhfpvghlejljwpvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZXh4aGZwdmdobGVqbGp3cHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MDg2NDUsImV4cCI6MjA4NTI4NDY0NX0.M107rJ9Ji17zAyd8Jolt5GQFZmu9vvAG1UiIq0GQh8U";
const AUTH_COOKIE_DOMAIN = import.meta.env.VITE_AUTH_COOKIE_DOMAIN ?? ".brain-bbqs.org";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: cookieStorage(AUTH_COOKIE_DOMAIN),
    storageKey: "bbqs-auth-session",
    persistSession: true,
    autoRefreshToken: true,
  },
  // NOTE: do NOT add a global custom header here (e.g. X-BBQS-Client). supabase-js applies
  // global headers to EVERY request including functions.invoke, and each edge function's
  // hand-written CORS allow-list would then reject the preflight ("Request header field
  // x-bbqs-client is not allowed"), breaking every function (nih-grants/projects, chat,
  // add-project, …). Provenance tagging for KG-site writes must be done per-write, not globally.
});